let count = 7;
const znachenie = "Значение";
const dvoeto4ie = ":";
console.log(znachenie + dvoeto4ie,count);
let cvadratcount = count **2;
const kvadratzn = "Квадрат этого значения";
console.log(kvadratzn + dvoeto4ie,cvadratcount);
let cubcount = count**3;
const cubzn = "Куб этого значения";
console.log(cubzn + dvoeto4ie,cubcount);
let countc = 25;
const grcels = "\u00B0C";
let result = countc * 9 / 5 + 32;
const grfar = "\u00B0F";
const ravno = "равно";
console.log(countc + grcels, ravno,result + grfar);
let countf = 73;
let result2 = ((countf - 32) * 5) / 9;
console.log(countf + grfar, ravno,result2 + grcels);